version: '3.7'
services:
  spike-tasks:
    container_name: spike-tasks
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  spike-tasks-prod:
    container_name: spike-tasks-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - '1337:80'