name: js-commit
on: [push]
jobs:
  build-lint-test-client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3.0.0
      - run: npm ci
      - run: npm run lint
      - run: npm test
